# Generated by Django 5.2.1 on 2025-08-01 11:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0005_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1), ('carousel', 3)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('author', 0)]], {}), 3: ('wagtail.blocks.StreamBlock', [[('image', 1), ('quotation', 2)]], {})}, null=True),
        ),
    ]
