# Generated by Django 5.2.1 on 2025-08-06 07:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0008_author_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('info', 0), ('faq', 4), ('text', 5), ('image', 6), ('doc', 7), ('page', 8), ('author', 9), ('call_to_action_1', 13), ('carousel', 15)], blank=True, block_lookup={0: ('blocks.blocks.InfoBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 3: ('wagtail.blocks.StructBlock', [[('question', 1), ('answer', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': 'Frequently Asked Questions', 'max_num': 5, 'min_num': 1}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 8: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 9: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blogpages.Author',), {}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 11: ('wagtail.blocks.PageChooserBlock', (), {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('text', 10), ('page', 11), ('button_text', 12)]], {'label': 'CTA #1'}), 14: ('wagtail.blocks.StructBlock', [[('text', 5), ('author', 5)]], {}), 15: ('wagtail.blocks.StreamBlock', [[('image', 6), ('quotation', 14)]], {})}, null=True),
        ),
    ]
