# Generated by Django 5.2.1 on 2025-08-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0013_author_locked_author_locked_at_author_locked_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('can_edit_author_name', 'Can edit author name')]},
        ),
    ]
