# Generated by Django 5.2.5 on 2025-09-06 04:27

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel

class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0017_author_locale_author_translation_key'),
    ]

    operations = [
        BootstrapTranslatableModel('blogpages.Author'),
    ]
