# Generated by Django 5.2.1 on 2025-07-31 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0003_blogpagetags_blogdetail_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='body',
        ),
    ]
