# Generated by Django 5.2.1 on 2025-08-02 05:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0006_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1), ('doc', 2), ('page', 3), ('carousel', 5)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 3: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['home.HomePage'], 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('text', 0), ('author', 0)]], {}), 5: ('wagtail.blocks.StreamBlock', [[('image', 1), ('quotation', 4)]], {})}, null=True),
        ),
    ]
