# Generated by Django 5.2.1 on 2025-08-12 12:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0009_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('info', 0), ('faq', 1), ('text', 2), ('image', 3), ('doc', 4), ('page', 5), ('author', 6), ('call_to_action_1', 10), ('carousel', 14)], blank=True, block_lookup={0: ('blocks.blocks.InfoBlock', (), {}), 1: ('blocks.blocks.FAQListBlock', (), {}), 2: ('blocks.blocks.TextBlock', (), {}), 3: ('blocks.blocks.ImageBlock', (), {}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'group': 'Standalone Blocks'}), 5: ('wagtail.blocks.PageChooserBlock', (), {'group': 'Standalone Blocks', 'page_type': ['home.HomePage'], 'required': False}), 6: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blogpages.Author',), {}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 8: ('wagtail.blocks.PageChooserBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('text', 7), ('page', 8), ('button_text', 9)]], {}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 12: ('wagtail.blocks.TextBlock', (), {}), 13: ('wagtail.blocks.StructBlock', [[('text', 12), ('author', 12)]], {}), 14: ('wagtail.blocks.StreamBlock', [[('image', 11), ('quotation', 13)]], {})}, null=True),
        ),
    ]
