# Generated by Django 5.2.5 on 2025-08-30 11:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0014_alter_author_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
